# Identifiants du projet - à récupérer sur sonarcloud.io après avoir importé le repo
sonar.projectKey=Keox96_TournamentManager
sonar.organization=keox96

# Nom affiché sur SonarCloud
sonar.projectName=TournamentManager

# Sources et tests
sonar.sources=src
sonar.tests=tests

# Exclusions
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/migrations/**

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Version Python
sonar.python.version=3.13